my_tupla = (53,'p3rr0',7.4,True)
print(type(my_tupla))
print(my_tupla[1])
print(my_tupla.count(53))
print(my_tupla.index(True))
my_tupla = list(my_tupla)
print(type(my_tupla))
my_tupla.append('Ultimo')
print(my_tupla)
my_tupla = tuple(my_tupla)
print(type(my_tupla))
print(my_tupla)